// Code generated by protoc-gen-go. DO NOT EDIT.
// source: build.proto

package tio_control_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Sid                  int32    `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	BuildType            string   `protobuf:"bytes,4,opt,name=buildType,proto3" json:"buildType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Request) GetSid() int32 {
	if m != nil {
		return m.Sid
	}
	return 0
}

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetBuildType() string {
	if m != nil {
		return m.BuildType
	}
	return ""
}

type Reply struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{1}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Reply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Reply)(nil), "Reply")
}

func init() { proto.RegisterFile("build.proto", fileDescriptor_14ce178a580e4ede) }

var fileDescriptor_14ce178a580e4ede = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x3d, 0x6f, 0xc2, 0x30,
	0x10, 0x86, 0x9b, 0x42, 0x48, 0x73, 0x20, 0x84, 0x6e, 0xb2, 0x68, 0x07, 0x94, 0x09, 0xa9, 0xaa,
	0xd5, 0x8f, 0x7f, 0xc0, 0xd2, 0x85, 0xc9, 0x65, 0xa8, 0xba, 0x41, 0x7c, 0x8a, 0x2c, 0x85, 0x5c,
	0x6a, 0x1b, 0x24, 0xfe, 0x7d, 0xe5, 0x6b, 0x53, 0xb6, 0xf7, 0xb1, 0xdf, 0xf3, 0x63, 0x1d, 0x4c,
	0x0f, 0x27, 0xd7, 0x5a, 0xdd, 0x7b, 0x8e, 0xbc, 0x9c, 0xd6, 0xdc, 0x85, 0xf8, 0x0b, 0x55, 0x03,
	0x85, 0xa1, 0xef, 0x13, 0x85, 0x88, 0x0a, 0x8a, 0xbd, 0xb5, 0x9e, 0x42, 0x50, 0xd9, 0x2a, 0x5b,
	0x97, 0x66, 0x40, 0x5c, 0xc0, 0x28, 0x38, 0xab, 0x6e, 0x57, 0xd9, 0x3a, 0x37, 0x29, 0x22, 0xc2,
	0xb8, 0xdb, 0x1f, 0x49, 0x8d, 0xa4, 0x28, 0x19, 0x1f, 0xa0, 0x14, 0xcd, 0xee, 0xd2, 0x93, 0x1a,
	0xcb, 0xc5, 0xf5, 0xa0, 0x7a, 0x82, 0xdc, 0x50, 0xdf, 0x5e, 0xd2, 0x68, 0xcd, 0x96, 0xc4, 0x91,
	0x1b, 0xc9, 0x49, 0x70, 0x0c, 0x8d, 0x08, 0x4a, 0x93, 0xe2, 0xeb, 0x27, 0xcc, 0x36, 0x69, 0xf6,
	0x83, 0xfc, 0xd9, 0xd5, 0x84, 0xf7, 0x90, 0x0b, 0xe3, 0x9d, 0xfe, 0xfb, 0xef, 0x72, 0xa2, 0xe5,
	0xc1, 0xea, 0x06, 0x1f, 0xa1, 0x78, 0xa7, 0xb8, 0xe5, 0x26, 0xe0, 0x5c, 0xef, 0x1c, 0x6f, 0xb9,
	0x19, 0x4a, 0xb3, 0x7f, 0x96, 0xea, 0x73, 0xb6, 0x59, 0x7c, 0xcd, 0xa3, 0x63, 0x5d, 0x73, 0x17,
	0x3d, 0xb7, 0xfa, 0xfc, 0x72, 0x98, 0xc8, 0x2a, 0xde, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe8,
	0x8c, 0x04, 0x3a, 0x26, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BuildServiceClient is the client API for BuildService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BuildServiceClient interface {
	Build(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	GetLogs(ctx context.Context, in *TioLogRequest, opts ...grpc.CallOption) (BuildService_GetLogsClient, error)
}

type buildServiceClient struct {
	cc *grpc.ClientConn
}

func NewBuildServiceClient(cc *grpc.ClientConn) BuildServiceClient {
	return &buildServiceClient{cc}
}

func (c *buildServiceClient) Build(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/BuildService/Build", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildServiceClient) GetLogs(ctx context.Context, in *TioLogRequest, opts ...grpc.CallOption) (BuildService_GetLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BuildService_serviceDesc.Streams[0], "/BuildService/GetLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &buildServiceGetLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BuildService_GetLogsClient interface {
	Recv() (*TioLogReply, error)
	grpc.ClientStream
}

type buildServiceGetLogsClient struct {
	grpc.ClientStream
}

func (x *buildServiceGetLogsClient) Recv() (*TioLogReply, error) {
	m := new(TioLogReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BuildServiceServer is the server API for BuildService service.
type BuildServiceServer interface {
	Build(context.Context, *Request) (*Reply, error)
	GetLogs(*TioLogRequest, BuildService_GetLogsServer) error
}

// UnimplementedBuildServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBuildServiceServer struct {
}

func (*UnimplementedBuildServiceServer) Build(ctx context.Context, req *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Build not implemented")
}
func (*UnimplementedBuildServiceServer) GetLogs(req *TioLogRequest, srv BuildService_GetLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetLogs not implemented")
}

func RegisterBuildServiceServer(s *grpc.Server, srv BuildServiceServer) {
	s.RegisterService(&_BuildService_serviceDesc, srv)
}

func _BuildService_Build_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).Build(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BuildService/Build",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).Build(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildService_GetLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TioLogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BuildServiceServer).GetLogs(m, &buildServiceGetLogsServer{stream})
}

type BuildService_GetLogsServer interface {
	Send(*TioLogReply) error
	grpc.ServerStream
}

type buildServiceGetLogsServer struct {
	grpc.ServerStream
}

func (x *buildServiceGetLogsServer) Send(m *TioLogReply) error {
	return x.ServerStream.SendMsg(m)
}

var _BuildService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BuildService",
	HandlerType: (*BuildServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Build",
			Handler:    _BuildService_Build_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetLogs",
			Handler:       _BuildService_GetLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "build.proto",
}
