// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package tio_control_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SrvMeta struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Env                  map[string]string `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SrvMeta) Reset()         { *m = SrvMeta{} }
func (m *SrvMeta) String() string { return proto.CompactTextString(m) }
func (*SrvMeta) ProtoMessage()    {}
func (*SrvMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *SrvMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SrvMeta.Unmarshal(m, b)
}
func (m *SrvMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SrvMeta.Marshal(b, m, deterministic)
}
func (m *SrvMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SrvMeta.Merge(m, src)
}
func (m *SrvMeta) XXX_Size() int {
	return xxx_messageInfo_SrvMeta.Size(m)
}
func (m *SrvMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_SrvMeta.DiscardUnknown(m)
}

var xxx_messageInfo_SrvMeta proto.InternalMessageInfo

func (m *SrvMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SrvMeta) GetEnv() map[string]string {
	if m != nil {
		return m.Env
	}
	return nil
}

func init() {
	proto.RegisterType((*SrvMeta)(nil), "SrvMeta")
	proto.RegisterMapType((map[string]string)(nil), "SrvMeta.EnvEntry")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0xbb, 0x4b, 0x04, 0x31,
	0x10, 0x87, 0xdd, 0x5d, 0x1f, 0x77, 0x73, 0x2a, 0x67, 0xb8, 0x62, 0xd9, 0xea, 0x38, 0x41, 0xae,
	0x0a, 0x78, 0x82, 0x88, 0x85, 0x85, 0xba, 0xa5, 0xcd, 0xee, 0xda, 0xd8, 0xc5, 0x38, 0x45, 0x30,
	0xc9, 0x84, 0x18, 0x03, 0xf1, 0xaf, 0x97, 0x7d, 0x75, 0xbf, 0xef, 0x9b, 0x61, 0x1e, 0x70, 0x2e,
	0xc9, 0x18, 0xb2, 0xdc, 0x79, 0x0a, 0x54, 0xad, 0x24, 0xd9, 0x9f, 0x30, 0xc2, 0xee, 0x0f, 0xce,
	0x5a, 0x1f, 0xdf, 0x30, 0x08, 0xc6, 0xe0, 0xd8, 0x0a, 0x83, 0x65, 0xb6, 0xcd, 0xf6, 0xcb, 0x66,
	0xc8, 0xec, 0x1a, 0x0a, 0xb4, 0xb1, 0xcc, 0xb7, 0xc5, 0x7e, 0x75, 0xb8, 0xe2, 0x53, 0x2b, 0xaf,
	0x6d, 0xac, 0x6d, 0xf0, 0xa9, 0xe9, 0xab, 0xd5, 0x3d, 0x2c, 0x66, 0xc1, 0xd6, 0x50, 0x7c, 0x63,
	0x9a, 0x66, 0xf4, 0x91, 0x6d, 0xe0, 0x24, 0x0a, 0xfd, 0x8b, 0x65, 0x3e, 0xb8, 0x11, 0x1e, 0xf3,
	0x87, 0xec, 0xf0, 0x04, 0x9b, 0x4e, 0xd1, 0x2b, 0x3a, 0x4d, 0xe9, 0x85, 0x8c, 0x69, 0xd1, 0x47,
	0x25, 0x91, 0xdd, 0xc0, 0xc5, 0xbb, 0xfb, 0x12, 0x01, 0xe7, 0xcb, 0x16, 0xf3, 0xe2, 0x6a, 0xc9,
	0x3b, 0x45, 0x0d, 0x3a, 0x9d, 0x76, 0x47, 0xcf, 0xeb, 0x8f, 0xcb, 0xa0, 0x88, 0x4b, 0xb2, 0xc1,
	0x93, 0xe6, 0xf1, 0xf6, 0xf3, 0x74, 0x78, 0xea, 0xee, 0x3f, 0x00, 0x00, 0xff, 0xff, 0xc3, 0xf0,
	0x40, 0x55, 0xf1, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TioDeployCommServiceClient is the client API for TioDeployCommService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TioDeployCommServiceClient interface {
	UpdateSrvMeta(ctx context.Context, in *SrvMeta, opts ...grpc.CallOption) (*TioReply, error)
}

type tioDeployCommServiceClient struct {
	cc *grpc.ClientConn
}

func NewTioDeployCommServiceClient(cc *grpc.ClientConn) TioDeployCommServiceClient {
	return &tioDeployCommServiceClient{cc}
}

func (c *tioDeployCommServiceClient) UpdateSrvMeta(ctx context.Context, in *SrvMeta, opts ...grpc.CallOption) (*TioReply, error) {
	out := new(TioReply)
	err := c.cc.Invoke(ctx, "/TioDeployCommService/UpdateSrvMeta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TioDeployCommServiceServer is the server API for TioDeployCommService service.
type TioDeployCommServiceServer interface {
	UpdateSrvMeta(context.Context, *SrvMeta) (*TioReply, error)
}

// UnimplementedTioDeployCommServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTioDeployCommServiceServer struct {
}

func (*UnimplementedTioDeployCommServiceServer) UpdateSrvMeta(ctx context.Context, req *SrvMeta) (*TioReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSrvMeta not implemented")
}

func RegisterTioDeployCommServiceServer(s *grpc.Server, srv TioDeployCommServiceServer) {
	s.RegisterService(&_TioDeployCommService_serviceDesc, srv)
}

func _TioDeployCommService_UpdateSrvMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SrvMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TioDeployCommServiceServer).UpdateSrvMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TioDeployCommService/UpdateSrvMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TioDeployCommServiceServer).UpdateSrvMeta(ctx, req.(*SrvMeta))
	}
	return interceptor(ctx, in, info, handler)
}

var _TioDeployCommService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TioDeployCommService",
	HandlerType: (*TioDeployCommServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateSrvMeta",
			Handler:    _TioDeployCommService_UpdateSrvMeta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common.proto",
}
