// Code generated by protoc-gen-go. DO NOT EDIT.
// source: const.proto

package tio_control_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JobStatus int32

const (
	JobStatus_BuildSucc    JobStatus = 0
	JobStatus_BuildFailed  JobStatus = 1
	JobStatus_BuildIng     JobStatus = 2
	JobStatus_DeployIng    JobStatus = 3
	JobStatus_DeploySuc    JobStatus = 4
	JobStatus_DeployFailed JobStatus = 5
)

var JobStatus_name = map[int32]string{
	0: "BuildSucc",
	1: "BuildFailed",
	2: "BuildIng",
	3: "DeployIng",
	4: "DeploySuc",
	5: "DeployFailed",
}

var JobStatus_value = map[string]int32{
	"BuildSucc":    0,
	"BuildFailed":  1,
	"BuildIng":     2,
	"DeployIng":    3,
	"DeploySuc":    4,
	"DeployFailed": 5,
}

func (x JobStatus) String() string {
	return proto.EnumName(JobStatus_name, int32(x))
}

func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5adb9555099c2688, []int{0}
}

type CommonRespCode int32

const (
	CommonRespCode_RespSucc  CommonRespCode = 0
	CommonRespCode_RespFaild CommonRespCode = -1
)

var CommonRespCode_name = map[int32]string{
	0:  "RespSucc",
	-1: "RespFaild",
}

var CommonRespCode_value = map[string]int32{
	"RespSucc":  0,
	"RespFaild": -1,
}

func (x CommonRespCode) String() string {
	return proto.EnumName(CommonRespCode_name, int32(x))
}

func (CommonRespCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5adb9555099c2688, []int{1}
}

type TioReply struct {
	Code                 CommonRespCode `protobuf:"varint,1,opt,name=code,proto3,enum=CommonRespCode" json:"code,omitempty"`
	Msg                  string         `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TioReply) Reset()         { *m = TioReply{} }
func (m *TioReply) String() string { return proto.CompactTextString(m) }
func (*TioReply) ProtoMessage()    {}
func (*TioReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5adb9555099c2688, []int{0}
}

func (m *TioReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TioReply.Unmarshal(m, b)
}
func (m *TioReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TioReply.Marshal(b, m, deterministic)
}
func (m *TioReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TioReply.Merge(m, src)
}
func (m *TioReply) XXX_Size() int {
	return xxx_messageInfo_TioReply.Size(m)
}
func (m *TioReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TioReply.DiscardUnknown(m)
}

var xxx_messageInfo_TioReply proto.InternalMessageInfo

func (m *TioReply) GetCode() CommonRespCode {
	if m != nil {
		return m.Code
	}
	return CommonRespCode_RespSucc
}

func (m *TioReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type TioUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Passwd               string   `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TioUserRequest) Reset()         { *m = TioUserRequest{} }
func (m *TioUserRequest) String() string { return proto.CompactTextString(m) }
func (*TioUserRequest) ProtoMessage()    {}
func (*TioUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5adb9555099c2688, []int{1}
}

func (m *TioUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TioUserRequest.Unmarshal(m, b)
}
func (m *TioUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TioUserRequest.Marshal(b, m, deterministic)
}
func (m *TioUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TioUserRequest.Merge(m, src)
}
func (m *TioUserRequest) XXX_Size() int {
	return xxx_messageInfo_TioUserRequest.Size(m)
}
func (m *TioUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TioUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TioUserRequest proto.InternalMessageInfo

func (m *TioUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TioUserRequest) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type TioUserReply struct {
	Code                 CommonRespCode `protobuf:"varint,1,opt,name=Code,proto3,enum=CommonRespCode" json:"Code,omitempty"`
	Token                *TioToken      `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	User                 *TioUserInfo   `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TioUserReply) Reset()         { *m = TioUserReply{} }
func (m *TioUserReply) String() string { return proto.CompactTextString(m) }
func (*TioUserReply) ProtoMessage()    {}
func (*TioUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5adb9555099c2688, []int{2}
}

func (m *TioUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TioUserReply.Unmarshal(m, b)
}
func (m *TioUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TioUserReply.Marshal(b, m, deterministic)
}
func (m *TioUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TioUserReply.Merge(m, src)
}
func (m *TioUserReply) XXX_Size() int {
	return xxx_messageInfo_TioUserReply.Size(m)
}
func (m *TioUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TioUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_TioUserReply proto.InternalMessageInfo

func (m *TioUserReply) GetCode() CommonRespCode {
	if m != nil {
		return m.Code
	}
	return CommonRespCode_RespSucc
}

func (m *TioUserReply) GetToken() *TioToken {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *TioUserReply) GetUser() *TioUserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type TioUserInfo struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TioUserInfo) Reset()         { *m = TioUserInfo{} }
func (m *TioUserInfo) String() string { return proto.CompactTextString(m) }
func (*TioUserInfo) ProtoMessage()    {}
func (*TioUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5adb9555099c2688, []int{3}
}

func (m *TioUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TioUserInfo.Unmarshal(m, b)
}
func (m *TioUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TioUserInfo.Marshal(b, m, deterministic)
}
func (m *TioUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TioUserInfo.Merge(m, src)
}
func (m *TioUserInfo) XXX_Size() int {
	return xxx_messageInfo_TioUserInfo.Size(m)
}
func (m *TioUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TioUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TioUserInfo proto.InternalMessageInfo

func (m *TioUserInfo) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type TioToken struct {
	AccessKey            string   `protobuf:"bytes,1,opt,name=accessKey,proto3" json:"accessKey,omitempty"`
	SecretKey            string   `protobuf:"bytes,2,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
	Bucket               string   `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	CallBackUrl          string   `protobuf:"bytes,4,opt,name=callBackUrl,proto3" json:"callBackUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TioToken) Reset()         { *m = TioToken{} }
func (m *TioToken) String() string { return proto.CompactTextString(m) }
func (*TioToken) ProtoMessage()    {}
func (*TioToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_5adb9555099c2688, []int{4}
}

func (m *TioToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TioToken.Unmarshal(m, b)
}
func (m *TioToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TioToken.Marshal(b, m, deterministic)
}
func (m *TioToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TioToken.Merge(m, src)
}
func (m *TioToken) XXX_Size() int {
	return xxx_messageInfo_TioToken.Size(m)
}
func (m *TioToken) XXX_DiscardUnknown() {
	xxx_messageInfo_TioToken.DiscardUnknown(m)
}

var xxx_messageInfo_TioToken proto.InternalMessageInfo

func (m *TioToken) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

func (m *TioToken) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *TioToken) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *TioToken) GetCallBackUrl() string {
	if m != nil {
		return m.CallBackUrl
	}
	return ""
}

func init() {
	proto.RegisterEnum("JobStatus", JobStatus_name, JobStatus_value)
	proto.RegisterEnum("CommonRespCode", CommonRespCode_name, CommonRespCode_value)
	proto.RegisterType((*TioReply)(nil), "TioReply")
	proto.RegisterType((*TioUserRequest)(nil), "TioUserRequest")
	proto.RegisterType((*TioUserReply)(nil), "TioUserReply")
	proto.RegisterType((*TioUserInfo)(nil), "TioUserInfo")
	proto.RegisterType((*TioToken)(nil), "TioToken")
}

func init() { proto.RegisterFile("const.proto", fileDescriptor_5adb9555099c2688) }

var fileDescriptor_5adb9555099c2688 = []byte{
	// 385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xb1, 0x6e, 0xdb, 0x30,
	0x10, 0xad, 0x62, 0x39, 0x08, 0x4f, 0xae, 0x43, 0x70, 0x08, 0x3c, 0x14, 0x88, 0xa1, 0x2e, 0x41,
	0x06, 0x01, 0x4d, 0x81, 0x4e, 0x5d, 0x6a, 0x17, 0x05, 0xd2, 0x6e, 0xb4, 0xb2, 0x74, 0x93, 0xa9,
	0x6b, 0x40, 0x98, 0xd2, 0xa9, 0x22, 0x99, 0xc2, 0x5b, 0xff, 0xbc, 0x05, 0x29, 0xb6, 0x4e, 0x97,
	0x6a, 0x10, 0xee, 0xbd, 0xc7, 0x7b, 0x77, 0x8f, 0x20, 0x14, 0x8a, 0x7a, 0xeb, 0xaa, 0x61, 0x24,
	0x47, 0xe5, 0x07, 0xb8, 0xa8, 0x35, 0x49, 0x1c, 0xcc, 0x51, 0xbc, 0x86, 0x5c, 0x51, 0x8b, 0xab,
	0x6c, 0x9d, 0xdd, 0x2c, 0xef, 0x2e, 0xab, 0x2d, 0x75, 0x1d, 0xf5, 0x12, 0xed, 0xb0, 0xa5, 0x16,
	0x65, 0x14, 0x05, 0x87, 0x59, 0x67, 0x1f, 0x57, 0x67, 0xeb, 0xec, 0x86, 0xc9, 0x50, 0x96, 0xef,
	0x61, 0x59, 0x6b, 0x7a, 0xb0, 0x38, 0x4a, 0xfc, 0xee, 0xd1, 0x3a, 0x21, 0x20, 0xef, 0x9b, 0x6e,
	0x32, 0x62, 0x32, 0xd6, 0xe2, 0x0a, 0xce, 0x87, 0xc6, 0xda, 0x1f, 0x6d, 0x6a, 0x4d, 0xa8, 0x7c,
	0x82, 0xc5, 0xdf, 0xee, 0xb4, 0xc4, 0xf6, 0x7f, 0x4b, 0x84, 0xbf, 0xb8, 0x86, 0xb9, 0xa3, 0x03,
	0xf6, 0xd1, 0xab, 0xb8, 0x63, 0x55, 0xad, 0xa9, 0x0e, 0x84, 0x9c, 0x78, 0xb1, 0x86, 0xdc, 0x5b,
	0x1c, 0x57, 0xb3, 0xa8, 0x2f, 0xaa, 0x34, 0xe2, 0xbe, 0xff, 0x46, 0x32, 0x2a, 0xe5, 0x35, 0x14,
	0xcf, 0xc8, 0x10, 0xcb, 0xeb, 0x36, 0x4e, 0x9d, 0xcb, 0x50, 0x96, 0x3f, 0xb3, 0x78, 0x35, 0xd1,
	0x56, 0xbc, 0x02, 0xd6, 0x28, 0x85, 0xd6, 0x7e, 0xc1, 0x63, 0x8a, 0x75, 0x22, 0x82, 0x6a, 0x51,
	0x8d, 0xe8, 0x82, 0x3a, 0xc5, 0x3b, 0x11, 0x21, 0xf9, 0xde, 0xab, 0x03, 0xba, 0xb8, 0x0d, 0x93,
	0x09, 0x89, 0x35, 0x14, 0xaa, 0x31, 0x66, 0xd3, 0xa8, 0xc3, 0xc3, 0x68, 0x56, 0x79, 0x14, 0x9f,
	0x53, 0xb7, 0x1a, 0xd8, 0x67, 0xda, 0xef, 0x5c, 0xe3, 0xbc, 0x15, 0x2f, 0x81, 0x6d, 0xbc, 0x36,
	0xed, 0xce, 0x2b, 0xc5, 0x5f, 0x88, 0x4b, 0x28, 0x22, 0xfc, 0xd4, 0x68, 0x83, 0x2d, 0xcf, 0xc4,
	0x02, 0x2e, 0x22, 0x71, 0xdf, 0x3f, 0xf2, 0xb3, 0x70, 0xfa, 0x23, 0x0e, 0x86, 0x8e, 0x01, 0xce,
	0x4e, 0x70, 0xe7, 0x15, 0xcf, 0x05, 0x87, 0xc5, 0x04, 0x53, 0xf7, 0xfc, 0xf6, 0x1d, 0x2c, 0xff,
	0xbd, 0xe9, 0xe0, 0x17, 0xea, 0x34, 0xee, 0x0a, 0x58, 0x40, 0xe1, 0x7c, 0xcb, 0x7f, 0xfd, 0xf9,
	0xb2, 0x0d, 0xff, 0xba, 0x74, 0x9a, 0x2a, 0x45, 0xbd, 0x1b, 0xc9, 0x54, 0x4f, 0x6f, 0xf6, 0xe7,
	0xf1, 0x61, 0xbd, 0xfd, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x23, 0x15, 0xdd, 0x67, 0x02, 0x00,
	0x00,
}
