// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deploy.proto

package tio_control_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeployRequest struct {
	Image                string   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Sid                  int32    `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployRequest) Reset()         { *m = DeployRequest{} }
func (m *DeployRequest) String() string { return proto.CompactTextString(m) }
func (*DeployRequest) ProtoMessage()    {}
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f09e103004e384, []int{0}
}

func (m *DeployRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployRequest.Unmarshal(m, b)
}
func (m *DeployRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployRequest.Marshal(b, m, deterministic)
}
func (m *DeployRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployRequest.Merge(m, src)
}
func (m *DeployRequest) XXX_Size() int {
	return xxx_messageInfo_DeployRequest.Size(m)
}
func (m *DeployRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeployRequest proto.InternalMessageInfo

func (m *DeployRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *DeployRequest) GetSid() int32 {
	if m != nil {
		return m.Sid
	}
	return 0
}

type SrvMeta struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SrvMeta) Reset()         { *m = SrvMeta{} }
func (m *SrvMeta) String() string { return proto.CompactTextString(m) }
func (*SrvMeta) ProtoMessage()    {}
func (*SrvMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f09e103004e384, []int{1}
}

func (m *SrvMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SrvMeta.Unmarshal(m, b)
}
func (m *SrvMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SrvMeta.Marshal(b, m, deterministic)
}
func (m *SrvMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SrvMeta.Merge(m, src)
}
func (m *SrvMeta) XXX_Size() int {
	return xxx_messageInfo_SrvMeta.Size(m)
}
func (m *SrvMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_SrvMeta.DiscardUnknown(m)
}

var xxx_messageInfo_SrvMeta proto.InternalMessageInfo

func (m *SrvMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*DeployRequest)(nil), "DeployRequest")
	proto.RegisterType((*SrvMeta)(nil), "SrvMeta")
}

func init() { proto.RegisterFile("deploy.proto", fileDescriptor_05f09e103004e384) }

var fileDescriptor_05f09e103004e384 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x49, 0x2d, 0xc8,
	0xc9, 0xaf, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0xe2, 0x4e, 0xce, 0xcf, 0x2b, 0x2e, 0x81,
	0x70, 0x94, 0xcc, 0xb9, 0x78, 0x5d, 0xc0, 0x92, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42,
	0x22, 0x5c, 0xac, 0x99, 0xb9, 0x89, 0xe9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10,
	0x8e, 0x90, 0x00, 0x17, 0x73, 0x71, 0x66, 0x8a, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x88,
	0xa9, 0x24, 0xcb, 0xc5, 0x1e, 0x5c, 0x54, 0xe6, 0x9b, 0x5a, 0x92, 0x28, 0x24, 0xc4, 0xc5, 0x92,
	0x97, 0x98, 0x0b, 0xd3, 0x01, 0x66, 0x1b, 0xa5, 0x70, 0x09, 0x84, 0x64, 0xe6, 0x43, 0x8c, 0x0e,
	0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0xd2, 0xe0, 0xe2, 0xf4, 0x4b, 0x2d, 0x87, 0x88, 0x09,
	0xf1, 0xe9, 0xa1, 0xd8, 0x2b, 0xc5, 0xa9, 0x17, 0x92, 0x99, 0x1f, 0x94, 0x5a, 0x90, 0x53, 0xa9,
	0xc4, 0x20, 0xa4, 0xc6, 0xc5, 0x1b, 0x5a, 0x90, 0x92, 0x58, 0x92, 0x0a, 0xb3, 0x82, 0x43, 0x0f,
	0xca, 0x42, 0x51, 0xe7, 0x24, 0x10, 0xc5, 0x57, 0x92, 0x99, 0xaf, 0x97, 0x9c, 0x9f, 0x57, 0x52,
	0x94, 0x9f, 0xa3, 0x57, 0x66, 0x98, 0xc4, 0x06, 0xf6, 0x96, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0xc4, 0x53, 0x44, 0x46, 0xf3, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TioDeployServiceClient is the client API for TioDeployService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TioDeployServiceClient interface {
	NewDeploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*TioReply, error)
	UpdateSrvMeta(ctx context.Context, in *SrvMeta, opts ...grpc.CallOption) (*TioReply, error)
}

type tioDeployServiceClient struct {
	cc *grpc.ClientConn
}

func NewTioDeployServiceClient(cc *grpc.ClientConn) TioDeployServiceClient {
	return &tioDeployServiceClient{cc}
}

func (c *tioDeployServiceClient) NewDeploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*TioReply, error) {
	out := new(TioReply)
	err := c.cc.Invoke(ctx, "/TioDeployService/NewDeploy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tioDeployServiceClient) UpdateSrvMeta(ctx context.Context, in *SrvMeta, opts ...grpc.CallOption) (*TioReply, error) {
	out := new(TioReply)
	err := c.cc.Invoke(ctx, "/TioDeployService/UpdateSrvMeta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TioDeployServiceServer is the server API for TioDeployService service.
type TioDeployServiceServer interface {
	NewDeploy(context.Context, *DeployRequest) (*TioReply, error)
	UpdateSrvMeta(context.Context, *SrvMeta) (*TioReply, error)
}

// UnimplementedTioDeployServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTioDeployServiceServer struct {
}

func (*UnimplementedTioDeployServiceServer) NewDeploy(ctx context.Context, req *DeployRequest) (*TioReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewDeploy not implemented")
}
func (*UnimplementedTioDeployServiceServer) UpdateSrvMeta(ctx context.Context, req *SrvMeta) (*TioReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSrvMeta not implemented")
}

func RegisterTioDeployServiceServer(s *grpc.Server, srv TioDeployServiceServer) {
	s.RegisterService(&_TioDeployService_serviceDesc, srv)
}

func _TioDeployService_NewDeploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TioDeployServiceServer).NewDeploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TioDeployService/NewDeploy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TioDeployServiceServer).NewDeploy(ctx, req.(*DeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TioDeployService_UpdateSrvMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SrvMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TioDeployServiceServer).UpdateSrvMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TioDeployService/UpdateSrvMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TioDeployServiceServer).UpdateSrvMeta(ctx, req.(*SrvMeta))
	}
	return interceptor(ctx, in, info, handler)
}

var _TioDeployService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TioDeployService",
	HandlerType: (*TioDeployServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewDeploy",
			Handler:    _TioDeployService_NewDeploy_Handler,
		},
		{
			MethodName: "UpdateSrvMeta",
			Handler:    _TioDeployService_UpdateSrvMeta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deploy.proto",
}
